// Generated by scripts/extract-codex-contracts.ts. Do not edit.
export const codexContractFixture = {
  catalog: {
    commit: "f1aac1e885f676a1129f2da0c46a3dba86392fc6",
    declarations: {
      "gpt-5.6-luna": "v1",
      "gpt-5.6-sol": "v2",
      "gpt-5.6-terra": "v2",
      "gpt-6-astra": "v2",
    },
  },
  commit: "389dd5645944891b65e4ca584125bbb0c852d352",
  sources: [
    "codex-rs/models-manager/models.json",
    "codex-rs/core/src/config/mod.rs",
    "codex-rs/core/src/tools/spec_plan.rs",
    "codex-rs/core/src/tools/handlers/multi_agents_spec.rs",
  ],
  v1: {
    namespace: "multi_agent_v1",
    tools: ["close_agent", "resume_agent", "send_input", "spawn_agent", "wait_agent"],
  },
  v2: {
    namespace: "collaboration",
    stockSpawnOutputProperties: ["task_name"],
    stockSpawnProperties: ["fork_turns", "message", "model", "reasoning_effort", "task_name"],
    tools: [
      "followup_task",
      "interrupt_agent",
      "list_agents",
      "send_message",
      "spawn_agent",
      "wait_agent",
    ],
  },
} as const;
