// Generated by scripts/extract-codex-contracts.ts. Do not edit.
export const codexContractFixture = {
  catalog: {
    commit: "b412ff32c417f855c2b2d1581b77058eed87c84b",
    declarations: {
      "gpt-5.6-luna": "v1",
      "gpt-5.6-sol": "v2",
      "gpt-5.6-terra": "v2",
      "gpt-6-astra": "v2",
      "gpt-6-luna": "v2",
      "gpt-6-sol": "v2",
    },
  },
  commit: "36f0dbe796d9bb1a18a0fc0640ed08b3e1d54564",
  sources: [
    "codex-rs/models-manager/models.json",
    "codex-rs/core/src/config/mod.rs",
    "codex-rs/core/src/tools/spec_plan.rs",
    "codex-rs/core/src/tools/handlers/multi_agents_spec.rs",
  ],
  v1: {
    namespace: "multi_agent_v1",
    tools: ["close_agent", "resume_agent", "send_input", "spawn_agent", "wait_agent"],
  },
  v2: {
    namespace: "collaboration",
    stockSpawnOutputProperties: ["task_name"],
    stockSpawnProperties: ["fork_turns", "message", "model", "reasoning_effort", "task_name"],
    tools: [
      "followup_task",
      "interrupt_agent",
      "list_agents",
      "send_message",
      "spawn_agent",
      "wait_agent",
    ],
  },
} as const;
